# Generated by Django 5.1 on 2024-09-15 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-placed_at', 'customer'), 'permissions': (('cancel_order', 'Can cancel order'),)},
        ),
    ]
