# Generated by Django 5.1 on 2024-09-16 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('user__last_name', 'user__first_name'),
                     'permissions': (('view_history', 'Can view history'),)},
        ),
    ]
