# Generated by Django 5.1 on 2024-09-09 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0009_cartitem_cart_uuid_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_uuid', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
