# Generated by Django 5.1 on 2024-09-09 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0010_alter_cartitem_unique_together_remove_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_uuid',
            new_name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
