# Generated by Django 5.1 on 2024-09-09 20:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0012_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
